from ROOT import *

signal = TFile('signal125.root')
qcd = TFile('qcd.root')


d1s_signal = signal.Get('d1s')
d1s_qcd = qcd.Get('d1s')
d1s_qcd.SetStats(0)
d1s_qcd.Scale(1.0/d1s_qcd.Integral())
d1s_signal.Scale(1.0/d1s_signal.Integral())
d1s_qcd.SetLineColor(kBlue)
d1s_signal.SetLineColor(kBlack)
d1s_qcd.SetMaximum(max(d1s_qcd.GetMaximum(), d1s_signal.GetMaximum())*1.2)
c1 = TCanvas()
d1s_qcd.Draw('hist')
d1s_signal.Draw('hist same')
d1s_qcd.SetTitle('distance 1 squared')
d1s_qcd.GetYaxis().SetTitle('scaled to Integral = 1')
leg1 = TLegend(0.6,0.8,0.9,0.9)
leg1.AddEntry(d1s_signal, 'Signal 125 MC', 'l')
leg1.AddEntry(d1s_qcd, 'QCD MC', 'l')
leg1.Draw('same')

d2s_signal = signal.Get('d2s')
d2s_qcd = qcd.Get('d2s')
d2s_qcd.SetStats(0)
d2s_qcd.Scale(1.0/d2s_qcd.Integral())
d2s_signal.Scale(1.0/d2s_signal.Integral())
d2s_qcd.SetLineColor(kBlue)
d2s_signal.SetLineColor(kBlack)
d2s_qcd.SetMaximum(max(d2s_qcd.GetMaximum(), d2s_signal.GetMaximum())*1.2)
c2 = TCanvas()
d2s_qcd.Draw('hist')
d2s_signal.Draw('hist same')
d2s_qcd.SetTitle('distance 2 squared')
d2s_qcd.GetYaxis().SetTitle('scaled to Integral = 1')
leg2 = TLegend(0.6,0.8,0.9,0.9)
leg2.AddEntry(d2s_signal, 'Signal 125 MC', 'l')
leg2.AddEntry(d2s_qcd, 'QCD MC', 'l')
leg2.Draw('same')

d3s_signal = signal.Get('d3s')
d3s_qcd = qcd.Get('d3s')
d3s_qcd.SetStats(0)
d3s_qcd.Scale(1.0/d3s_qcd.Integral())
d3s_signal.Scale(1.0/d3s_signal.Integral())
d3s_qcd.SetLineColor(kBlue)
d3s_signal.SetLineColor(kBlack)
d3s_qcd.SetMaximum(max(d3s_qcd.GetMaximum(), d3s_signal.GetMaximum())*1.2)
c3 = TCanvas()
d3s_qcd.Draw('hist')
d3s_signal.Draw('hist same')
d3s_qcd.SetTitle('distance 3 squared')
d3s_qcd.GetYaxis().SetTitle('scaled to Integral = 1')
leg3 = TLegend(0.6,0.8,0.9,0.9)
leg3.AddEntry(d3s_signal, 'Signal 125 MC', 'l')
leg3.AddEntry(d3s_qcd, 'QCD MC', 'l')
leg3.Draw('same')
